
(define (call-the-cops)
  (lambda (x)
    "The cops is called"))
(define (make-account balance password)
  (define (withdraw amount)
    (if (>= balance amount)
      (begin (set! balance (- balance amount))
             balance)
      "Insufficient funds"))
  (define (deposit input-pwd amount)
    (set! balance (+ balance amount))
    balance)
  (define try 6)
  (define (dispatch input-pwd m)
    (if (eq? input-pwd password)
      (cond 
        ((eq? m 'withdraw) withdraw)
        ((eq? m 'deposit) deposit)
        (else (error "Unknown request == MAKE-ACCOUNT" m)))
      (if (= try 0)
        (call-the-cops)
        (begin (set! try (- try 1))
          (lambda (x) "Incorrect password")))))
    dispatch)

